# Generated by Django 3.0.7 on 2020-06-15 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtribuicaoTecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(verbose_name='Horário da atribuição')),
            ],
        ),
        migrations.CreateModel(
            name='MudancaStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(verbose_name='Horário da mudança do status')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('estimativa_tempo', models.TimeField(blank=True, null=True, verbose_name='tempo estimado')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=46, verbose_name='Nome do status')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=46, verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=46, verbose_name='Nome do usuario')),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('responsavel', models.ManyToManyField(through='solicitacoes.AtribuicaoTecnico', to='solicitacoes.Tecnico')),
                ('status', models.ManyToManyField(through='solicitacoes.MudancaStatus', to='solicitacoes.Status')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='mudancastatus',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.Solicitacao'),
        ),
        migrations.AddField(
            model_name='mudancastatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.Status'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satifacao', models.PositiveSmallIntegerField(verbose_name='Satifação com o atendimento')),
                ('tempo', models.PositiveSmallIntegerField(verbose_name='Tempo da solução')),
                ('qualidade', models.PositiveSmallIntegerField(verbose_name='Satifação qualidade da solução')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.Solicitacao')),
            ],
        ),
        migrations.AddField(
            model_name='atribuicaotecnico',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.Solicitacao'),
        ),
        migrations.AddField(
            model_name='atribuicaotecnico',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitacoes.Tecnico'),
        ),
    ]
