# Generated by Django 3.0.7 on 2020-06-15 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnico',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=46, verbose_name='Nome do tecnico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnico',
            name='senha',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
